In [1]:
""""create a dictionary of your own data and convert it to a dataframe
do some basic exploratory analysis on the data"""

'"create a dictionary of your own data and convert it to a dataframe\ndo some basic exploratory analysis on the data'

In [2]:
import pandas as pd
data = {"Housing_type": ["Single_room", "apartment","studio", "Bangalow"],
              "Number_of_rooms": ["1", "2", "1", "3"],
              "Housing_condition": ["good_condition", "fully_furnished", "small", "poor_condition"],
              "Location": ["Augsburg", "Landshut", "München", "Passau"],
              }

In [3]:
dt = pd.DataFrame(data)

In [4]:
print (dt)

  Housing_type Number_of_rooms Housing_condition  Location
0  Single_room               1    good_condition  Augsburg
1    apartment               2   fully_furnished  Landshut
2       studio               1             small   München
3     Bangalow               3    poor_condition    Passau

In [5]:
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Housing_type       4 non-null      object
 1   Number_of_rooms    4 non-null      object
 2   Housing_condition  4 non-null      object
 3   Location           4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes
None

In [6]:
print(dt.describe())

       Housing_type Number_of_rooms Housing_condition  Location
count             4               4                 4         4
unique            4               3                 4         4
top     Single_room               1    good_condition  Augsburg
freq              1               2                 1         1

In [7]:
import pandas as pd

data = {
    'Product': ['Apple', 'Banana', 'Orange', 'Grapes'],
    'Price': [120, 40, 60, 150],
    'Quantity': [10, 20, 15, 5]
}

df = pd.DataFrame(data)

print(df)

  Product  Price  Quantity
0   Apple    120        10
1  Banana     40        20
2  Orange     60        15
3  Grapes    150         5

In [8]:
print(df.describe())

            Price   Quantity
count    4.000000   4.000000
mean    92.500000  12.500000
std     51.234754   6.454972
min     40.000000   5.000000
25%     55.000000   8.750000
50%     90.000000  12.500000
75%    127.500000  16.250000
max    150.000000  20.000000

In [9]:
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Housing_type       4 non-null      object
 1   Number_of_rooms    4 non-null      object
 2   Housing_condition  4 non-null      object
 3   Location           4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes
None

In [10]:
# Introduction to data cleaning
#1 subset columns and rows
# basic pandas data manpuli
#selecting specific data  points based on conditions

In [11]:
import pandas as pd

In [70]:
datapath = "/root/ds_tutorial/Test-repository/WhatsgoodlyData-6.csv"

data = pd.read_csv(datapath)

In [13]:
data

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067
4,What social platform has influenced your onlin...,Mobile,Global results,NaN,947,0.354
...,...,...,...,...,...,...
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074
1449,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,NaN,492,0.412

In [14]:
data.head(10)

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067
4,What social platform has influenced your onlin...,Mobile,Global results,NaN,947,0.354
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000
6,What social platform has influenced your onlin...,Web,Web,Instagram,0,0.000
7,What social platform has influenced your onlin...,Web,Web,Snapchat,0,0.000
8,What social platform has influenced your onlin...,Web,Web,Twitter,0,0.000
9,What social platform has influenced your onlin...,Web,Web,NaN,2,1.000

In [15]:
data.tail()

,Question,Segment Type,Segment Description,Answer,Count,Percentage
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074
1449,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,NaN,492,0.412

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Question             1450 non-null   object
 1   Segment Type         1450 non-null   object
 2   Segment Description  1450 non-null   object
 3   Answer               1160 non-null   object
 4   Count                1450 non-null   int64
 5   Percentage           1450 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 68.1+ KB

In [17]:
data.dtypes

Question                object
Segment Type            object
Segment Description     object
Answer                  object
Count                    int64
Percentage             float64
dtype: object

In [18]:
data.columns

Index(['Question', 'Segment Type', 'Segment Description', 'Answer', 'Count',
       'Percentage'],
      dtype='object')

In [19]:
type(data["Answer"]) #data series

pandas.core.series.Series

In [20]:
data[["Answer"]] #dataframe

         Answer
0      Facebook
1     Instagram
2      Snapchat
3       Twitter
4           NaN
...         ...
1445   Facebook
1446  Instagram
1447   Snapchat
1448    Twitter
1449        NaN

[1450 rows x 1 columns]

In [21]:
data[["Answer"]].columns

Index(['Answer'], dtype='object')

In [22]:
data.Answer

0        Facebook
1       Instagram
2        Snapchat
3         Twitter
4             NaN
          ...
1445     Facebook
1446    Instagram
1447     Snapchat
1448      Twitter
1449          NaN
Name: Answer, Length: 1450, dtype: object

In [23]:
# Row subsetting
# loc or iloc
#loc-- takes starting index and stop index /lower index/limit to upper index 
#iloc-- takes the positions of the row-- start/lower limit to upper limit but the upper position is not included in subsetting the rows

In [24]:
data.loc[10:25]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
10,What social platform has influenced your onlin...,Gender,Female voters,Facebook,222,0.199
11,What social platform has influenced your onlin...,Gender,Female voters,Instagram,535,0.480
12,What social platform has influenced your onlin...,Gender,Female voters,Snapchat,29,0.026
13,What social platform has influenced your onlin...,Gender,Female voters,Twitter,57,0.051
14,What social platform has influenced your onlin...,Gender,Female voters,NaN,271,0.243
15,What social platform has influenced your onlin...,Gender,Male voters,Facebook,326,0.209
16,What social platform has influenced your onlin...,Gender,Male voters,Instagram,380,0.243
17,What social platform has influenced your onlin...,Gender,Male voters,Snapchat,56,0.036
18,What social platform has influenced your onlin...,Gender,Male voters,Twitter,122,0.078
19,What social platform has influenced your onlin...,Gender,Male voters,NaN,678,0.434
20,What social platform has influenced your onlin...,University,University of Delaware,Facebook,1,0.333
21,What social platform has influenced your onlin...,University,University of Delaware,Instagram,1,0.333
22,What social platform has influenced your onlin...,University,University of Delaware,Snapchat,0,0.000
23,What social platform has influenced your onlin...,University,University of Delaware,Twitter,0,0.000
24,What social platform has influenced your onlin...,University,University of Delaware,NaN,1,0.333
25,What social platform has influenced your onlin...,University,University of Pennsylvania,Facebook,1,0.250

In [25]:
data.iloc[10:25]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
10,What social platform has influenced your onlin...,Gender,Female voters,Facebook,222,0.199
11,What social platform has influenced your onlin...,Gender,Female voters,Instagram,535,0.480
12,What social platform has influenced your onlin...,Gender,Female voters,Snapchat,29,0.026
13,What social platform has influenced your onlin...,Gender,Female voters,Twitter,57,0.051
14,What social platform has influenced your onlin...,Gender,Female voters,NaN,271,0.243
15,What social platform has influenced your onlin...,Gender,Male voters,Facebook,326,0.209
16,What social platform has influenced your onlin...,Gender,Male voters,Instagram,380,0.243
17,What social platform has influenced your onlin...,Gender,Male voters,Snapchat,56,0.036
18,What social platform has influenced your onlin...,Gender,Male voters,Twitter,122,0.078
19,What social platform has influenced your onlin...,Gender,Male voters,NaN,678,0.434
20,What social platform has influenced your onlin...,University,University of Delaware,Facebook,1,0.333
21,What social platform has influenced your onlin...,University,University of Delaware,Instagram,1,0.333
22,What social platform has influenced your onlin...,University,University of Delaware,Snapchat,0,0.000
23,What social platform has influenced your onlin...,University,University of Delaware,Twitter,0,0.000
24,What social platform has influenced your onlin...,University,University of Delaware,NaN,1,0.333

In [26]:
data.iloc[:,1:]

     Segment Type           Segment Description     Answer  Count  Percentage
0          Mobile                Global results   Facebook    548       0.205
1          Mobile                Global results  Instagram    916       0.342
2          Mobile                Global results   Snapchat     86       0.032
3          Mobile                Global results    Twitter    179       0.067
4          Mobile                Global results        NaN    947       0.354
...           ...                           ...        ...    ...         ...
1445       Custom  Sexual orientation? Straight   Facebook    215       0.180
1446       Custom  Sexual orientation? Straight  Instagram    354       0.297
1447       Custom  Sexual orientation? Straight   Snapchat     44       0.037
1448       Custom  Sexual orientation? Straight    Twitter     88       0.074
1449       Custom  Sexual orientation? Straight        NaN    492       0.412

[1450 rows x 5 columns]

In [27]:
data.iloc[25:51, 1:3]

   Segment Type             Segment Description
25   University      University of Pennsylvania
26   University      University of Pennsylvania
27   University      University of Pennsylvania
28   University      University of Pennsylvania
29   University      University of Pennsylvania
30   University            Students of New York
31   University            Students of New York
32   University            Students of New York
33   University            Students of New York
34   University            Students of New York
35   University  University of Central Arkansas
36   University  University of Central Arkansas
37   University  University of Central Arkansas
38   University  University of Central Arkansas
39   University  University of Central Arkansas
40   University         Northeastern University
41   University         Northeastern University
42   University         Northeastern University
43   University         Northeastern University
44   University         Northeastern University
45   University       West Virginia University
46   University       West Virginia University
47   University       West Virginia University
48   University       West Virginia University
49   University       West Virginia University
50   University     Northern Arizona University

In [28]:
#Import the data and show the first and last 10 data samples
# select the first and last data columns
# Select 100th data sample to 200th data sample
# Perform basic statistics on the result of 3

In [29]:
#shape
data.shape

(1450, 6)

In [30]:
#data[condition]
data[data["Answer"]=="Facebook"]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000
10,What social platform has influenced your onlin...,Gender,Female voters,Facebook,222,0.199
15,What social platform has influenced your onlin...,Gender,Male voters,Facebook,326,0.209
20,What social platform has influenced your onlin...,University,University of Delaware,Facebook,1,0.333
...,...,...,...,...,...,...
1425,What social platform has influenced your onlin...,Custom,What's your GPA? Above 4.0 😏,Facebook,19,0.131
1430,What social platform has influenced your onlin...,Custom,Graduation Year 2019,Facebook,221,0.262
1435,What social platform has influenced your onlin...,Custom,Graduation Year 2020,Facebook,74,0.155
1440,What social platform has influenced your onlin...,Custom,closely identify as? White,Facebook,352,0.224
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180

In [31]:
#mutiple conditions
data[(data["Answer"]=="Facebook") & (data["Percentage"]>0.3)]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
20,What social platform has influenced your onlin...,University,University of Delaware,Facebook,1,0.333
40,What social platform has influenced your onlin...,University,Northeastern University,Facebook,1,0.500
50,What social platform has influenced your onlin...,University,Northern Arizona University,Facebook,1,1.000
55,What social platform has influenced your onlin...,University,"University of California, Santa Barbara",Facebook,1,1.000
100,What social platform has influenced your onlin...,University,University of Toronto,Facebook,1,0.333
120,What social platform has influenced your onlin...,University,Wesleyan University,Facebook,1,1.000
150,What social platform has influenced your onlin...,University,Wake Forest University,Facebook,1,1.000
165,What social platform has influenced your onlin...,University,University of Central Missouri,Facebook,1,0.333
180,What social platform has influenced your onlin...,University,Colorado Academy,Facebook,1,0.500
195,What social platform has influenced your onlin...,University,Lock Haven University,Facebook,1,1.000
210,What social platform has influenced your onlin...,University,Vanderbilt University,Facebook,15,0.375
225,What social platform has influenced your onlin...,University,Emory University,Facebook,15,0.319
230,What social platform has influenced your onlin...,University,University of Richmond,Facebook,3,0.600
240,What social platform has influenced your onlin...,University,University of British Columbia,Facebook,1,0.333
255,What social platform has influenced your onlin...,University,"Westport, CT",Facebook,1,1.000
290,What social platform has influenced your onlin...,University,Tufts University,Facebook,4,0.400
355,What social platform has influenced your onlin...,University,Santa Clara University,Facebook,1,0.333
380,What social platform has influenced your onlin...,University,Virginia Tech,Facebook,1,0.333
385,What social platform has influenced your onlin...,University,Syracuse University,Facebook,1,0.333
425,What social platform has influenced your onlin...,University,University of Texas,Facebook,13,0.342
480,What social platform has influenced your onlin...,University,University of New Hampshire,Facebook,3,0.429
525,What social platform has influenced your onlin...,University,University of Colorado Boulder,Facebook,1,0.333
535,What social platform has influenced your onlin...,University,Villanova University,Facebook,2,1.000
555,What social platform has influenced your onlin...,University,Dartmouth College,Facebook,7,0.412
570,What social platform has influenced your onlin...,University,Michigan State University,Facebook,1,0.500
600,What social platform has influenced your onlin...,University,Truman State University,Facebook,18,0.360
625,What social platform has influenced your onlin...,University,"University of California, Los Angeles",Facebook,1,1.000
675,What social platform has influenced your onlin...,University,Blinn College,Facebook,1,1.000
695,What social platform has influenced your onlin...,University,Stellenbosch University,Facebook,1,0.500
715,What social platform has influenced your onlin...,University,University of West Georgia,Facebook,1,1.000
725,What social platform has influenced your onlin...,University,University of Connecticut,Facebook,1,1.000
765,What social platform has influenced your onlin...,University,Michigan Technological University,Facebook,1,1.000
810,What social platform has influenced your onlin...,University,University of Tampa,Facebook,1,1.000
855,What social platform has influenced your onlin...,University,UMass Amherst,Facebook,1,0.500
990,What social platform has influenced your onlin...,Custom,Are you a? Student Trekker,Facebook,1,1.000
1145,What social platform has influenced your onlin...,Custom,What's your major? Comm / marketing,Facebook,37,0.308
1320,What social platform has influenced your onlin...,Custom,clubs / organizations? More than one major org,Facebook,14,0.304

In [32]:
data[(data["Answer"]=="Facebook") | (data["Percentage"]>0.3)]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
4,What social platform has influenced your onlin...,Mobile,Global results,NaN,947,0.354
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000
9,What social platform has influenced your onlin...,Web,Web,NaN,2,1.000
...,...,...,...,...,...,...
1440,What social platform has influenced your onlin...,Custom,closely identify as? White,Facebook,352,0.224
1441,What social platform has influenced your onlin...,Custom,closely identify as? White,Instagram,498,0.317
1444,What social platform has influenced your onlin...,Custom,closely identify as? White,NaN,573,0.365
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180
1449,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,NaN,492,0.412

In [33]:
data[(data["Segment Type"]=="Mobile") & (data["Count"]>500)]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
4,What social platform has influenced your onlin...,Mobile,Global results,NaN,947,0.354

In [34]:
data[(data["Segment Type"]=="Web") | (data["Answer"]=="Instagram")]

,Question,Segment Type,Segment Description,Answer,Count,Percentage
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000
6,What social platform has influenced your onlin...,Web,Web,Instagram,0,0.000
7,What social platform has influenced your onlin...,Web,Web,Snapchat,0,0.000
8,What social platform has influenced your onlin...,Web,Web,Twitter,0,0.000
...,...,...,...,...,...,...
1426,What social platform has influenced your onlin...,Custom,What's your GPA? Above 4.0 😏,Instagram,55,0.379
1431,What social platform has influenced your onlin...,Custom,Graduation Year 2019,Instagram,291,0.345
1436,What social platform has influenced your onlin...,Custom,Graduation Year 2020,Instagram,150,0.314
1441,What social platform has influenced your onlin...,Custom,closely identify as? White,Instagram,498,0.317
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297

In [35]:
#sorting
#sort by  is a sequence means its a list
data.sort_values(by=["Answer"])#automatically is in ascending order

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1030,What social platform has influenced your onlin...,Custom,you a virgin? Yes,Facebook,104,0.179
315,What social platform has influenced your onlin...,University,Ohio University,Facebook,0,0.000
625,What social platform has influenced your onlin...,University,"University of California, Los Angeles",Facebook,1,1.000
310,What social platform has influenced your onlin...,University,University of Georgia,Facebook,0,0.000
...,...,...,...,...,...,...
1429,What social platform has influenced your onlin...,Custom,What's your GPA? Above 4.0 😏,NaN,56,0.386
1434,What social platform has influenced your onlin...,Custom,Graduation Year 2019,NaN,262,0.310
1439,What social platform has influenced your onlin...,Custom,Graduation Year 2020,NaN,191,0.400
1444,What social platform has influenced your onlin...,Custom,closely identify as? White,NaN,573,0.365
1449,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,NaN,492,0.412

In [36]:
#For descending   ,ascending= False
data.sort_values(by=["Answer"], ascending=False)

,Question,Segment Type,Segment Description,Answer,Count,Percentage
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074
553,What social platform has influenced your onlin...,University,University of Wisconsin-Madison,Twitter,7,0.068
1298,What social platform has influenced your onlin...,Custom,Mac or PC? PC 💻,Twitter,54,0.072
598,What social platform has influenced your onlin...,University,Texas Christian University,Twitter,3,0.130
593,What social platform has influenced your onlin...,University,University of Missouri,Twitter,4,0.167
...,...,...,...,...,...,...
1429,What social platform has influenced your onlin...,Custom,What's your GPA? Above 4.0 😏,NaN,56,0.386
1434,What social platform has influenced your onlin...,Custom,Graduation Year 2019,NaN,262,0.310
1439,What social platform has influenced your onlin...,Custom,Graduation Year 2020,NaN,191,0.400
1444,What social platform has influenced your onlin...,Custom,closely identify as? White,NaN,573,0.365
1449,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,NaN,492,0.412

In [37]:
#For sorting multiply colums
data.sort_values(by=["Answer", "Count"], ascending=False)

,Question,Segment Type,Segment Description,Answer,Count,Percentage
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067
1388,What social platform has influenced your onlin...,Custom,I'm in? College,Twitter,151,0.065
18,What social platform has influenced your onlin...,Gender,Male voters,Twitter,122,0.078
1028,What social platform has influenced your onlin...,Custom,you a virgin? No,Twitter,108,0.064
1338,What social platform has influenced your onlin...,Custom,clubs / organizations? No,Twitter,105,0.068
...,...,...,...,...,...,...
869,What social platform has influenced your onlin...,University,Kutztown University,NaN,0,0.000
874,What social platform has influenced your onlin...,University,University of Mississippi,NaN,0,0.000
889,What social platform has influenced your onlin...,University,Shippensburg University,NaN,0,0.000
989,What social platform has influenced your onlin...,Custom,Are you a? SVB team member,NaN,0,0.000
994,What social platform has influenced your onlin...,Custom,Are you a? Student Trekker,NaN,0,0.000

In [38]:
#get number of missing values
data.isnull().sum()

Question                 0
Segment Type             0
Segment Description      0
Answer                 290
Count                    0
Percentage               0
dtype: int64

In [39]:
data_rm = data.dropna()

In [40]:
data_rm

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000
...,...,...,...,...,...,...
1443,What social platform has influenced your onlin...,Custom,closely identify as? White,Twitter,102,0.065
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074

In [41]:
#In place 
data.dropna(inplace=True)

In [42]:
data

,Question,Segment Type,Segment Description,Answer,Count,Percentage
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000
...,...,...,...,...,...,...
1443,What social platform has influenced your onlin...,Custom,closely identify as? White,Twitter,102,0.065
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074

In [43]:
#knowing the value count
data.value_counts()

Question                                                        Segment Type  Segment Description         Answer     Count  Percentage
What social platform has influenced your online shopping most?  Web           Web                         Twitter    0      0.000         1
                                                                Custom        Are you a? SVB team member  Facebook   0      0.000         1
                                                                                                          Instagram  0      0.000         1
                                                                                                          Snapchat   0      0.000         1
                                                                                                          Twitter    0      0.000         1
                                                                                                                                         ..
                                                                              Are you single? No          Twitter    22     0.071         1
                                                                              Are you single? Yes         Facebook   128    0.164         1
                                                                                                          Instagram  245    0.314         1
                                                                                                          Snapchat   25     0.032         1
                                                                                                          Twitter    57     0.073         1
Name: count, Length: 1160, dtype: int64

In [44]:
data[["Answer"]].value_counts()

Answer
Facebook     290
Instagram    290
Snapchat     290
Twitter      290
Name: count, dtype: int64

In [45]:
data[["Segment Type"]].value_counts()

Segment Type
University      696
Custom          448
Gender            8
Mobile            4
Web               4
Name: count, dtype: int64

In [46]:
data["Answer"].unique()

array(['Facebook', 'Instagram', 'Snapchat', 'Twitter'], dtype=object)

In [47]:
#Finding number of unique values
data["Answer"].nunique()

4

In [48]:
#find the number of segment descriptions
#find the types of segment description 
#For each segment decription value find the number of times they occur

In [49]:
#1
data["Segment Description"].nunique()

289

In [50]:
#2
data["Segment Description"].unique()

array(['Global results', 'Web', 'Female voters', 'Male voters',
       'University of Delaware', 'University of Pennsylvania',
       'Students of New York', 'University of Central Arkansas',
       'Northeastern University', 'West Virginia University ',
       'Northern Arizona University',
       'University of California, Santa Barbara', 'University of Memphis',
       'Auburn University', 'Randolph-Macon College', 'Wisconsin HS',
       'Penn State University', 'Case Western Reserve University',
       'Rutgers University', 'University of Oregon',
       'University of Toronto', 'State University of New York Geneso',
       'Carthage College', 'University of South Carolina',
       'Wesleyan University', 'Memorial University of Newfoundland',
       'University of Kansas', 'University of Redlands',
       'University of Arkansas', 'Richland High School',
       'Wake Forest University', 'Iowa State University',
       'Florida Gulf Coast University', 'University of Central Missouri',
       'California State University Long Beach', 'Chaparral High School',
       'Colorado Academy', 'United States Naval Academy',
       'University of Wisconsin-Whitewater', 'Lock Haven University',
       'Kalamazoo College', 'Stanford University',
       'Vanderbilt University', 'Chapman University',
       'Missouri State University', 'Emory University',
       'University of Richmond', 'Medford High School',
       'University of British Columbia', 'Colby College', 'Bates College',
       'Westport, CT', 'Whitman College', 'Thompson Rivers University ',
       'University of Central Florida', 'University of Montana ',
       'University of Nebraska', 'Whatsgoodly University',
       'Tufts University', 'Texas Tech University',
       'Kansas State University', 'University of Notre Dame',
       'University of Georgia', 'Ohio University',
       'Washington State University', 'Binghamtom University',
       'George Washington University', 'University of Alabama',
       'University of Florida', 'The College of New Jersey',
       'Florida State University', 'Santa Clara University',
       'Appalachian State University', 'Arbroath Academy',
       'Arkansas Tech University ', 'University of Rhode Island',
       'Virginia Tech', 'Syracuse University',
       'Cypress Creek High School', 'Union High School',
       'College of William and Mary', 'Ohio State University',
       'Gulf Breeze High School', 'Cal Poly San Luis Obispo',
       'Oklahoma State University ', 'University of Texas',
       'Hampden-Sydney College ', 'University of Arizona',
       'Coventry University', 'Rochester Institute of Technology',
       'Colgate University', 'Northwestern University',
       'Saginaw Valley State University', 'University of Michigan',
       'Boise State University', 'Cornell University',
       'University of New Hampshire', 'UMass Dartmouth',
       'High Point University', 'University of Minnesota',
       'Claremont McKenna College', 'University of Central Oklahoma',
       'Illinois State', 'University of Guelph', 'Queens University',
       'University of Colorado Boulder', 'University of Virginia',
       'Villanova University', 'Centre College',
       'Johns Hopkins University', 'University of Wisconsin-Madison',
       'Dartmouth College', 'Purdue University',
       'San Diego State University', 'Michigan State University',
       'Butler University', 'Indiana University',
       'University of California, Berkeley', 'University of Missouri',
       'Texas Christian University', 'Truman State University',
       'University of Illinois', 'University of Washington',
       'University of North Carolina', 'Miami University (Ohio)',
       'University of California, Los Angeles',
       'Wilfred Laurier University', 'University of California Riverside',
       'University of Iowa', 'University of California Irvine',
       'University of California, Davis', 'University of Waterloo',
       'Grand Valley State University', 'Baylor University',
       'Southern Methodist University', 'Blinn College',
       'Texas A&M University', 'Wellesley College',
       'Central Washington University', 'Stellenbosch University',
       'Universidad Nacional de Costa Rica', 'Kennesaw State University',
       'Newcastle University', 'University of West Georgia ',
       'Azusa Pacific University', 'University of Connecticut',
       'Boston University', 'Colorado State University',
       'Clemson University', 'University of Rochester',
       'James Madison University', 'Stephen F. Austin State University',
       'Loyola University Maryland', 'Michigan Technological University',
       'Texas State University', 'University of Tennessee at Chattanooga',
       'Seton Hall University', 'Roger Williams University',
       'Elon University', 'Emily Carr University of Art and Design',
       'United States Military Academy',
       'Indiana University of Pennsylvania', 'University of Tampa',
       'Essex Technical High School',
       'University of North Carolina at Greensboro',
       'Pinnacle High School', 'Baltimore City College',
       'New York University',
       'Indiana University-Purdue University Indianapolis',
       'Loyola Marymount University', 'University of Dayton',
       'UMass Amherst', 'Brock University', 'Kutztown University',
       'University of Mississippi', 'University of Mount Union',
       'Duke University', 'Shippensburg University',
       'guys, 5\'5" girls) Tall',
       'guys, 5\'5" girls) Medium (± 3 inches)',
       'guys, 5\'5" girls) Short', 'or private school? Private',
       'games a lot? Yes, console mostly',
       'your parents make? Upper class (> $240K)',
       'your parents make? Upper-middle class (~$160K',
       'your parents make? Middle / lower-middle class (~$90K)',
       'your parents make? Poor (< ~$50K) 😁',
       "What's your major? ME/EE/other engineer",
       'or private school? No school', 'or private school? Public',
       'you vote for? Donald Trump', 'you vote for? Hillary Clinton',
       "What's your major? Business/Econ/Finance",
       "What's your major? Pre-med", 'closely identify as? Asian',
       'Are you? None/Other', 'Are you? Jewish',
       'Are you a? SVB team member', 'Are you a? Student Trekker',
       'you a feminist? No', 'you a feminist? Yes', 'Are you single? No',
       'Are you single? Yes', 'student loan debt? No',
       'student loan debt? Yes', 'you a virgin? No', 'you a virgin? Yes',
       "you vote for? Didn't vote", 'you vote for? Writing in Bernie',
       'you vote for? Other', 'you vote for? Gary Johnson',
       'Sexual orientation? Confused', 'Sexual orientation? Bi',
       'Sexual orientation? Gay', 'in Greek life? No but I wanna be...',
       'your zodiac sign? Capricorn (Dec 22 - Jan 19)',
       'your zodiac sign? Sagittarius (Nov 22 - Dec 21)',
       'your zodiac sign? Scorpio (Oct 23 - Nov 21)',
       'your zodiac sign? Libra (Sep 23 - Oct 22)',
       'your zodiac sign? Virgo (Aug 23 - Sep 22)',
       'your zodiac sign? Leo (Jul 23 - Aug 22)',
       'your zodiac sign? Cancer (Jun 21 - Jul 22)',
       'your zodiac sign? Gemini (May 21 - Jun 20)',
       'your zodiac sign? Taurus (Apr 20 - May 20)',
       'your zodiac sign? Aries (Mar 21 - Apr 19)',
       'your zodiac sign? Pisces (Feb 19 - Mar 20)',
       'your zodiac sign? Aquarius (Jan 20-Feb 18)',
       'grow up speaking? English',
       'have a job? Nope, and not looking for one',
       "What's your major? Comm / marketing",
       'are you pursuing? Undecided', 'are you pursuing? Humanities',
       'do per month? About 1 hour', 'do per month? Less than an hour',
       'closely identify as? Other',
       'closely identify as? Native American',
       "What's your leaning? Liberal 🔷",
       "What's your leaning? Conservative 🐘", "I'm in? Other",
       "I'm in? Grad School", 'have a job? Yes, full-time',
       "What's your GPA? 3.0 to 4.0", "What's your GPA? Below 1.0 😁",
       'closely identify as? Black', 'Mac or PC? Other 🐧',
       'in Greek life? No!', 'Mac or PC? Mac 🖥',
       'in Greek life? Yes but regretting it', 'in Greek life? Yes!',
       'you vote for? Jill Stein', "What's your GPA? 2.0 to 3.0",
       "What's your GPA? 1.0 to 2.0", 'games a lot? No',
       'games a lot? Yes, mobile mostly', 'games a lot? Yes, PC mostly',
       "What's your major? Languages",
       "What's your major? Visual/performing arts",
       "What's your major? History",
       "have a job? No, but I'm searching for one", 'Mac or PC? PC 💻',
       "What's your major? Other",
       'grow up speaking? Some other language (comment)',
       'grow up speaking? Both', 'grow up speaking? Spanish',
       'clubs / organizations? More than one major org',
       'clubs / organizations? A major one',
       'clubs / organizations? A minor one', 'clubs / organizations? No',
       'do per month? More than 10 hours 😇',
       'do per month? 1 to 10 hours', 'closely identify as? Hispanic',
       'are you pursuing? Technical / engineering',
       "What's your major? Comp sci", "I'm in? Post-grad",
       'have a job? Yes, part-time',
       "What's your major? Political science / philosophy",
       "I'm in? College", "I'm in? High School",
       'do per month? Realistically, none',
       "What's your leaning? In-between", 'Are you? Muslim',
       'Are you? Christian', 'Graduation Year 2017',
       'Graduation Year 2018', "What's your GPA? Above 4.0 😏",
       'Graduation Year 2019', 'Graduation Year 2020',
       'closely identify as? White', 'Sexual orientation? Straight'],
      dtype=object)

In [51]:
data[["Segment Description"]].value_counts()

Segment Description
What's your major? Other       8
West Virginia University       4
Wesleyan University            4
Wellesley College              4
Web                            4
                              ..
Ohio State University          4
Northwestern University        4
Northern Arizona University    4
Northeastern University        4
Queens University              4
Name: count, Length: 289, dtype: int64

In [52]:
data["count_discount"] = data["Count"] * data ["Percentage"]

In [53]:
data

,Question,Segment Type,Segment Description,Answer,Count,Percentage,count_discount
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205,112.340
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342,313.272
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032,2.752
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067,11.993
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000,0.000
...,...,...,...,...,...,...,...
1443,What social platform has influenced your onlin...,Custom,closely identify as? White,Twitter,102,0.065,6.630
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180,38.700
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297,105.138
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037,1.628
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074,6.512

In [54]:
data["count_discount"] = data["Count"] -100 #data ["Percentage"]

In [55]:
import numpy as np

In [56]:
data["count_degree"] = np.where(data["Count"]>500, "high count", "low count")

In [57]:
data

,Question,Segment Type,Segment Description,Answer,Count,Percentage,count_discount,count_degree
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205,448,high count
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342,816,high count
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032,-14,low count
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067,79,low count
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000,-100,low count
...,...,...,...,...,...,...,...,...
1443,What social platform has influenced your onlin...,Custom,closely identify as? White,Twitter,102,0.065,2,low count
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180,115,low count
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297,254,low count
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037,-56,low count
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074,-12,low count

In [58]:
# when to save the orignal copy from the edited data
data_used = data.copy()

In [59]:
#combine both columns
data_used["segment_and_answer"] = data_used["Segment Type"]

In [60]:
data_used.nsmallest(10, columns="Count")

,Question,Segment Type,Segment Description,Answer,Count,Percentage,count_discount,count_degree,segment_and_answer
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.0,-100,low count,Web
6,What social platform has influenced your onlin...,Web,Web,Instagram,0,0.0,-100,low count,Web
7,What social platform has influenced your onlin...,Web,Web,Snapchat,0,0.0,-100,low count,Web
8,What social platform has influenced your onlin...,Web,Web,Twitter,0,0.0,-100,low count,Web
22,What social platform has influenced your onlin...,University,University of Delaware,Snapchat,0,0.0,-100,low count,University
23,What social platform has influenced your onlin...,University,University of Delaware,Twitter,0,0.0,-100,low count,University
27,What social platform has influenced your onlin...,University,University of Pennsylvania,Snapchat,0,0.0,-100,low count,University
28,What social platform has influenced your onlin...,University,University of Pennsylvania,Twitter,0,0.0,-100,low count,University
30,What social platform has influenced your onlin...,University,Students of New York,Facebook,0,0.0,-100,low count,University
35,What social platform has influenced your onlin...,University,University of Central Arkansas,Facebook,0,0.0,-100,low count,University

In [61]:
data_used.nlargest(5, columns="Count")

,Question,Segment Type,Segment Description,Answer,Count,Percentage,count_discount,count_degree,segment_and_answer
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342,816,high count,Mobile
1386,What social platform has influenced your onlin...,Custom,I'm in? College,Instagram,781,0.336,681,high count,Custom
1026,What social platform has influenced your onlin...,Custom,you a virgin? No,Instagram,579,0.341,479,high count,Custom
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205,448,high count,Mobile
1231,What social platform has influenced your onlin...,Custom,Mac or PC? Mac 🖥,Instagram,546,0.375,446,high count,Custom

In [62]:
data_used["Count"].mean()

np.float64(27.443103448275863)

In [63]:
data_used["Segment Type"].count()

np.int64(1160)

In [64]:
data_used["Segment Type"].value_counts()

Segment Type
University    696
Custom        448
Gender          8
Mobile          4
Web             4
Name: count, dtype: int64

In [65]:
data_used["Count"].sum()

np.int64(31834)

In [66]:
for rowindex, col in data_used.iterrows():
    print(col["Count"])
    if rowindex == 5:
        break

548
916
86
179
0

In [67]:
data_used

,Question,Segment Type,Segment Description,Answer,Count,Percentage,count_discount,count_degree,segment_and_answer
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205,448,high count,Mobile
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342,816,high count,Mobile
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032,-14,low count,Mobile
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067,79,low count,Mobile
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000,-100,low count,Web
...,...,...,...,...,...,...,...,...,...
1443,What social platform has influenced your onlin...,Custom,closely identify as? White,Twitter,102,0.065,2,low count,Custom
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180,115,low count,Custom
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297,254,low count,Custom
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037,-56,low count,Custom
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074,-12,low count,Custom

In [68]:
data_used.rename(columns={"Question": "Inquiry", "Answer": "Response"})

,Inquiry,Segment Type,Segment Description,Response,Count,Percentage,count_discount,count_degree,segment_and_answer
0,What social platform has influenced your onlin...,Mobile,Global results,Facebook,548,0.205,448,high count,Mobile
1,What social platform has influenced your onlin...,Mobile,Global results,Instagram,916,0.342,816,high count,Mobile
2,What social platform has influenced your onlin...,Mobile,Global results,Snapchat,86,0.032,-14,low count,Mobile
3,What social platform has influenced your onlin...,Mobile,Global results,Twitter,179,0.067,79,low count,Mobile
5,What social platform has influenced your onlin...,Web,Web,Facebook,0,0.000,-100,low count,Web
...,...,...,...,...,...,...,...,...,...
1443,What social platform has influenced your onlin...,Custom,closely identify as? White,Twitter,102,0.065,2,low count,Custom
1445,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Facebook,215,0.180,115,low count,Custom
1446,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Instagram,354,0.297,254,low count,Custom
1447,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Snapchat,44,0.037,-56,low count,Custom
1448,What social platform has influenced your onlin...,Custom,Sexual orientation? Straight,Twitter,88,0.074,-12,low count,Custom